# Generated by Django 4.1.6 on 2023-02-20 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_auc_list_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_base',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cur',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Bidinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_bid_set', to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bid_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bidings',
            field=models.ManyToManyField(related_name='prod_biding', through='auctions.Bidinglist', to='auctions.product'),
        ),
    ]
