# Generated by Django 4.1.6 on 2023-02-20 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_product_price_base_alter_product_price_cur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidinglist',
            name='bid_price',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=19),
        ),
        migrations.AddField(
            model_name='bidinglist',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_base',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cur',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
