# Generated by Django 4.1.6 on 2023-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bidinglist_bid_price_bidinglist_bid_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='prod_categories', to='auctions.categories'),
        ),
    ]
