# Generated by Django 4.1.6 on 2023-02-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_product_bids_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='archiveproduct',
            table='auctions_archive_product',
        ),
    ]
