# Generated by Django 4.1.6 on 2023-02-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_archiveproduct_bids_product_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveproduct',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bids',
        ),
    ]
